library(data.table)
library(ggplot2)
library(dplyr)
library(leaflet)
library(reshape2)
##all rds for plots and stuff
runoff_eu_info <-  na.omit(readRDS('./data/runoff_eu_info.rds'))
runoff_eu_day <- na.omit(readRDS('./data/runoff_eu_day.rds'))
runoff_eu_year <- na.omit(readRDS('./data/runoff_eu_year.rds'))
desc_stat <- readRDS('./source/desc_stat.rds')
runoff_estimated <- readRDS('./source/runoff_estimated.rds')
runoff_stats_newnew <- readRDS('./source/runoff_stats_newnew.rds')
runoff_eu_day <- readRDS('./source/runoff_eu_day.rds')
runoff_eu_day_est <- readRDS('source/runoff_eu_day.rds')
runoff_seasonal_aft80 <- readRDS('./source/runoff_seasonal_aft80.rds')
runoff_seasonal_bef80 <-readRDS('./source/runoff_seasonal_bef80.rds')
corr_mat_aft80 <- readRDS('./source/corr_mat_aft80.rds')
corr_mat_bef80 <- readRDS('./source/corr_mat_bef80.rds')
reg_plot_summer_bef80 <- readRDS('./source/reg_plot_summer_bef80.rds')
reg_plot_winter_bef80 <- readRDS('./source/reg_plot_winter_bef80.rds')
reg_plot_summer_aft80 <- readRDS('./source/reg_plot_summer_aft80.rds')
reg_plot_winter_aft80 <- readRDS('./source/reg_plot_winter_aft80.rds')